SELECT 
1 AS enterprise,
CASE WHEN immobilie.immobiliennr = '04SW' THEN 'Roswiesen' ELSE CASE WHEN immobilie.immobiliennr = '05SW' THEN 'Altwiesen' ELSE CASE WHEN immobilie.immobiliennr = '06SW' THEN 'Neuwiesen I' ELSE CASE WHEN immobilie.immobiliennr = '08SW' THEN 'Kronwiesen I' ELSE CASE WHEN immobilie.immobiliennr = '09SW' THEN 'Winterthurer-/Dübendorfstrasse' ELSE CASE WHEN immobilie.immobiliennr = '10SW' THEN 'Kronwiesen II' ELSE CASE WHEN immobilie.immobiliennr = '11SW' THEN 'Kronwiesen III' ELSE CASE WHEN immobilie.immobiliennr = '13SW' THEN 'Kronwiesen IV' ELSE CASE WHEN immobilie.immobiliennr = '14SW' THEN 'Neuwiesen II' ELSE CASE WHEN immobilie.immobiliennr = '15SW' THEN 'Luchswiesen I' ELSE CASE WHEN immobilie.immobiliennr = '16SW' THEN 'Luchswiesen II' ELSE CASE WHEN immobilie.immobiliennr = '17SB' THEN 'Gründhalden' ELSE CASE WHEN immobilie.immobiliennr = '18SW' THEN 'Ahorn' ELSE CASE WHEN immobilie.immobiliennr = '19SW' THEN 'Saatlen I' ELSE CASE WHEN immobilie.immobiliennr = '20SB' THEN 'Rümlangstrasse 1' ELSE CASE WHEN immobilie.immobiliennr = '21SB' THEN 'Hertenstein' ELSE CASE WHEN immobilie.immobiliennr = '22SW' THEN 'Neuwiesen III' ELSE CASE WHEN immobilie.immobiliennr = '23SW' THEN 'Saatlen II' ELSE CASE WHEN immobilie.immobiliennr = '26SB' THEN 'Am Katzenbach I' ELSE CASE WHEN immobilie.immobiliennr = '27SB' THEN 'Am Katzenbach II' ELSE CASE WHEN immobilie.immobiliennr = '28SB' THEN 'Am Katzenbach III' ELSE CASE WHEN immobilie.immobiliennr = '29SB' THEN 'Am Katzenbach IV' ELSE CASE WHEN immobilie.immobiliennr = '30ST' THEN 'Stadel I' ELSE CASE WHEN immobilie.immobiliennr = '31ST' THEN 'Stadel II' ELSE CASE WHEN immobilie.immobiliennr = '32OP' THEN 'Wrighthouse' ELSE CASE WHEN immobilie.immobiliennr = '33RL' THEN 'Pfaffenlebern' ELSE CASE WHEN immobilie.immobiliennr = '34SW' THEN 'Dübendorfstrasse 25' ELSE CASE WHEN immobilie.immobiliennr = '35SB' THEN 'Am Katzenbach V' ELSE CASE WHEN immobilie.immobiliennr = '36SW' THEN 'Im Schuppis I' ELSE CASE WHEN immobilie.immobiliennr = '41SW' THEN 'Dübendorfstrasse 23' ELSE CASE WHEN immobilie.immobiliennr = '07SB' THEN 'Birch-/Hertensteinstrasse' ELSE CASE WHEN immobilie.immobiliennr = '03SB' THEN 'Buchwiesen' ELSE CASE WHEN immobilie.immobiliennr = '24SW' THEN 'Alte Post' ELSE CASE WHEN immobilie.immobiliennr = '37SB' THEN 'Birchstrasse' ELSE CASE WHEN immobilie.immobiliennr = '38BÜ' THEN 'Glasi Bülach' ELSE CASE WHEN immobilie.immobiliennr = '39SW' THEN 'Im Schuppis II' ELSE CASE WHEN immobilie.immobiliennr = '40SW' THEN 'Riedacker' END END END END END END END END END END END END END END END END END END END END END END END END END END END END END END END END END END END END END AS divisionCaption,
CASE WHEN immobilie.immobiliennr LIKE '%SW' THEN CONCAT('1000', REPLACE(immobilie.immobiliennr, 'SW', '')) ELSE CASE WHEN immobilie.immobiliennr LIKE '%SB' THEN CONCAT('1010', REPLACE(immobilie.immobiliennr, 'SB', '')) ELSE CASE WHEN immobilie.immobiliennr LIKE '%ST' THEN CONCAT('1020', REPLACE(immobilie.immobiliennr, 'ST', '')) ELSE CASE WHEN immobilie.immobiliennr LIKE '%OP' THEN CONCAT('1030', REPLACE(immobilie.immobiliennr, 'OP', '')) ELSE CASE WHEN immobilie.immobiliennr LIKE '%RL' THEN CONCAT('1040', REPLACE(immobilie.immobiliennr, 'RL', '')) ELSE CASE WHEN immobilie.immobiliennr LIKE '%BÜ' THEN CONCAT('1050', REPLACE(immobilie.immobiliennr, 'BÜ', '')) ELSE '' END END END END END END AS division,
immobilie.immobez AS germanCaption,
CASE WHEN immobilie.immobiliennr LIKE '%SW' THEN CONCAT('1000', REPLACE(immobilie.immobiliennr, 'SW', '')) ELSE CASE WHEN immobilie.immobiliennr LIKE '%SB' THEN CONCAT('1010', REPLACE(immobilie.immobiliennr, 'SB', '')) ELSE CASE WHEN immobilie.immobiliennr LIKE '%ST' THEN CONCAT('1020', REPLACE(immobilie.immobiliennr, 'ST', '')) ELSE CASE WHEN immobilie.immobiliennr LIKE '%OP' THEN CONCAT('1030', REPLACE(immobilie.immobiliennr, 'OP', '')) ELSE CASE WHEN immobilie.immobiliennr LIKE '%RL' THEN CONCAT('1040', REPLACE(immobilie.immobiliennr, 'RL', '')) ELSE CASE WHEN immobilie.immobiliennr LIKE '%BÜ' THEN CONCAT('1050', REPLACE(immobilie.immobiliennr, 'BÜ', '')) ELSE '' END END END END END END AS realEstateNumber,
1 AS realEstateType,
CASE WHEN immobilie.immobiliennr = '04SW' THEN 'Roswiesen' ELSE CASE WHEN immobilie.immobiliennr = '05SW' THEN 'Altwiesen' ELSE CASE WHEN immobilie.immobiliennr = '06SW' THEN 'Neuwiesen I' ELSE CASE WHEN immobilie.immobiliennr = '08SW' THEN 'Kronwiesen I' ELSE CASE WHEN immobilie.immobiliennr = '09SW' THEN 'Winterthurer-/Dübendorfstrasse' ELSE CASE WHEN immobilie.immobiliennr = '10SW' THEN 'Kronwiesen II' ELSE CASE WHEN immobilie.immobiliennr = '11SW' THEN 'Kronwiesen III' ELSE CASE WHEN immobilie.immobiliennr = '13SW' THEN 'Kronwiesen IV' ELSE CASE WHEN immobilie.immobiliennr = '14SW' THEN 'Neuwiesen II' ELSE CASE WHEN immobilie.immobiliennr = '15SW' THEN 'Luchswiesen I' ELSE CASE WHEN immobilie.immobiliennr = '16SW' THEN 'Luchswiesen II' ELSE CASE WHEN immobilie.immobiliennr = '17SB' THEN 'Gründhalden' ELSE CASE WHEN immobilie.immobiliennr = '18SW' THEN 'Ahorn' ELSE CASE WHEN immobilie.immobiliennr = '19SW' THEN 'Saatlen I' ELSE CASE WHEN immobilie.immobiliennr = '20SB' THEN 'Rümlangstrasse 1' ELSE CASE WHEN immobilie.immobiliennr = '21SB' THEN 'Hertenstein' ELSE CASE WHEN immobilie.immobiliennr = '22SW' THEN 'Neuwiesen III' ELSE CASE WHEN immobilie.immobiliennr = '23SW' THEN 'Saatlen II' ELSE CASE WHEN immobilie.immobiliennr = '26SB' THEN 'Am Katzenbach I' ELSE CASE WHEN immobilie.immobiliennr = '27SB' THEN 'Am Katzenbach II' ELSE CASE WHEN immobilie.immobiliennr = '28SB' THEN 'Am Katzenbach III' ELSE CASE WHEN immobilie.immobiliennr = '29SB' THEN 'Am Katzenbach IV' ELSE CASE WHEN immobilie.immobiliennr = '30ST' THEN 'Stadel I' ELSE CASE WHEN immobilie.immobiliennr = '31ST' THEN 'Stadel II' ELSE CASE WHEN immobilie.immobiliennr = '32OP' THEN 'Wrighthouse' ELSE CASE WHEN immobilie.immobiliennr = '33RL' THEN 'Pfaffenlebern' ELSE CASE WHEN immobilie.immobiliennr = '34SW' THEN 'Dübendorfstrasse 25' ELSE CASE WHEN immobilie.immobiliennr = '35SB' THEN 'Am Katzenbach V' ELSE CASE WHEN immobilie.immobiliennr = '36SW' THEN 'Im Schuppis I' ELSE CASE WHEN immobilie.immobiliennr = '41SW' THEN 'Dübendorfstrasse 23' ELSE CASE WHEN immobilie.immobiliennr = '07SB' THEN 'Birch-/Hertensteinstrasse' ELSE CASE WHEN immobilie.immobiliennr = '03SB' THEN 'Buchwiesen' ELSE CASE WHEN immobilie.immobiliennr = '24SW' THEN 'Alte Post' ELSE CASE WHEN immobilie.immobiliennr = '37SB' THEN 'Birchstrasse' ELSE CASE WHEN immobilie.immobiliennr = '38BÜ' THEN 'Glasi Bülach' ELSE CASE WHEN immobilie.immobiliennr = '39SW' THEN 'Im Schuppis II' ELSE CASE WHEN immobilie.immobiliennr = '40SW' THEN 'Riedacker' END END END END END END END END END END END END END END END END END END END END END END END END END END END END END END END END END END END END END AS street,
immobilie.ort AS city,
immobilie.plz AS zip,
immobilie.tk_land AS canton,
immobilie.tk_staat AS country,
1 AS administrationType,
immobilie.immobiliennr As ImmoNr,
'' AS drAuthorityNumber,
'01.01.1900' AS MandateAcceptance,
'' AS mandateTermination,
'' AS realEstateCategory,
'' AS taxOpted,
'' AS optedPortion,
'' AS nameTagSupplierNumber,
'' AS federalBuildingIdentifier,
'' AS checklistNumber,
'' AS levelOwnerSwitch,
'' AS designation


FROM 
immobilie

WHERE 
immobilie.immobiliennr != '99VW'
AND NVL(immobilie.abdat, '31.12.9999') > '31.12.2022'