  CREATE TABLE "IMMO"."TEMP9" 
   (	"PARTNER_ID" VARCHAR2(20 BYTE), 
	"ID" NUMBER(*,0), 
	"AB_DATUM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  

INSERT INTO TEMP9
SELECT 
mv.partner_id,
ROW_NUMBER() OVER(ORDER BY partner_id),
MAX(BEGINNDAT)

FROM 
mv 

WHERE
NVL(mv.endedat, '31.12.9999') > SYSDATE 
AND mv.beginndat < SYSDATE 

GROUP BY 
partner_id